spring:
  application:
    name: core-common-contract-mgmt
    version: 1.0.0
    description: Contract Management Core Application
    team:
      name: Firefly Software Solutions Inc
      email: dev@getfirefly.io
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:https://app-firefly-config-server.dev.soon.es/}"